version: "3"
services:
  app-postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "app_dev"
      POSTGRES_PASSWORD: "e1bc9e7f864d"
    volumes:
      - ./localDBSetup:/docker-entrypoint-initdb.d
